/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.pomelo.tell;

public final class R {
    public static final class array {
        public static final int country_codes=0x7f0b0000;
    }
    public static final class attr {
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int confirm_logout=0x7f01000c;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int done_button_background=0x7f010006;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int done_button_text=0x7f010004;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int extra_fields=0x7f010001;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fetch_user_info=0x7f01000d;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int is_cropped=0x7f010011;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int login_text=0x7f01000e;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int logout_text=0x7f01000f;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int multi_select=0x7f010007;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>small</code></td><td>-2</td><td> Keep in sync with constants in ProfilePictureView </td></tr>
<tr><td><code>normal</code></td><td>-3</td><td></td></tr>
<tr><td><code>large</code></td><td>-4</td><td></td></tr>
</table>
         */
        public static final int preset_size=0x7f010010;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int radius_in_meters=0x7f010008;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int results_limit=0x7f010009;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int search_text=0x7f01000a;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int show_pictures=0x7f010000;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int show_search_box=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int show_title_bar=0x7f010002;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int title_bar_background=0x7f010005;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int title_text=0x7f010003;
    }
    public static final class color {
        public static final int com_facebook_blue=0x7f080002;
        public static final int com_facebook_loginview_text_color=0x7f080006;
        public static final int com_facebook_picker_search_bar_background=0x7f080000;
        public static final int com_facebook_picker_search_bar_text=0x7f080001;
        public static final int com_facebook_usersettingsfragment_connected_shadow_color=0x7f080004;
        public static final int com_facebook_usersettingsfragment_connected_text_color=0x7f080003;
        public static final int com_facebook_usersettingsfragment_not_connected_text_color=0x7f080005;
        public static final int contents_text=0x7f080007;
        public static final int encode_view=0x7f080008;
        public static final int possible_result_points=0x7f080009;
        /**  Android standard ICS color 
         */
        public static final int result_minor_text=0x7f08000a;
        public static final int result_points=0x7f08000b;
        /**  Android standard ICS color 
         */
        public static final int result_text=0x7f08000c;
        public static final int result_view=0x7f08000d;
        public static final int status_text=0x7f08000e;
        public static final int transparent=0x7f08000f;
        public static final int viewfinder_laser=0x7f080010;
        /**  Android standard ICS color 
         */
        public static final int viewfinder_mask=0x7f080011;
    }
    public static final class dimen {
        public static final int com_facebook_loginview_compound_drawable_padding=0x7f070008;
        public static final int com_facebook_loginview_padding_bottom=0x7f070007;
        public static final int com_facebook_loginview_padding_left=0x7f070004;
        public static final int com_facebook_loginview_padding_right=0x7f070005;
        public static final int com_facebook_loginview_padding_top=0x7f070006;
        public static final int com_facebook_loginview_text_size=0x7f070009;
        public static final int com_facebook_picker_divider_width=0x7f070001;
        public static final int com_facebook_picker_place_image_size=0x7f070000;
        public static final int com_facebook_profilepictureview_preset_size_large=0x7f07000c;
        public static final int com_facebook_profilepictureview_preset_size_normal=0x7f07000b;
        public static final int com_facebook_profilepictureview_preset_size_small=0x7f07000a;
        public static final int com_facebook_tooltip_horizontal_padding=0x7f07000d;
        public static final int com_facebook_usersettingsfragment_profile_picture_height=0x7f070003;
        public static final int com_facebook_usersettingsfragment_profile_picture_width=0x7f070002;
        public static final int half_padding=0x7f07000f;
        public static final int standard_padding=0x7f07000e;
    }
    public static final class drawable {
        public static final int com_facebook_button_blue=0x7f020000;
        public static final int com_facebook_button_blue_focused=0x7f020001;
        public static final int com_facebook_button_blue_normal=0x7f020002;
        public static final int com_facebook_button_blue_pressed=0x7f020003;
        public static final int com_facebook_button_check=0x7f020004;
        public static final int com_facebook_button_check_off=0x7f020005;
        public static final int com_facebook_button_check_on=0x7f020006;
        public static final int com_facebook_button_grey_focused=0x7f020007;
        public static final int com_facebook_button_grey_normal=0x7f020008;
        public static final int com_facebook_button_grey_pressed=0x7f020009;
        public static final int com_facebook_close=0x7f02000a;
        public static final int com_facebook_inverse_icon=0x7f02000b;
        public static final int com_facebook_list_divider=0x7f02000c;
        public static final int com_facebook_list_section_header_background=0x7f02000d;
        public static final int com_facebook_loginbutton_silver=0x7f02000e;
        public static final int com_facebook_logo=0x7f02000f;
        public static final int com_facebook_picker_default_separator_color=0x7f02002d;
        public static final int com_facebook_picker_item_background=0x7f020010;
        public static final int com_facebook_picker_list_focused=0x7f020011;
        public static final int com_facebook_picker_list_longpressed=0x7f020012;
        public static final int com_facebook_picker_list_pressed=0x7f020013;
        public static final int com_facebook_picker_list_selector=0x7f020014;
        public static final int com_facebook_picker_list_selector_background_transition=0x7f020015;
        public static final int com_facebook_picker_list_selector_disabled=0x7f020016;
        public static final int com_facebook_picker_magnifier=0x7f020017;
        public static final int com_facebook_picker_top_button=0x7f020018;
        public static final int com_facebook_place_default_icon=0x7f020019;
        public static final int com_facebook_profile_default_icon=0x7f02001a;
        public static final int com_facebook_profile_picture_blank_portrait=0x7f02001b;
        public static final int com_facebook_profile_picture_blank_square=0x7f02001c;
        public static final int com_facebook_tooltip_black_background=0x7f02001d;
        public static final int com_facebook_tooltip_black_bottomnub=0x7f02001e;
        public static final int com_facebook_tooltip_black_topnub=0x7f02001f;
        public static final int com_facebook_tooltip_black_xout=0x7f020020;
        public static final int com_facebook_tooltip_blue_background=0x7f020021;
        public static final int com_facebook_tooltip_blue_bottomnub=0x7f020022;
        public static final int com_facebook_tooltip_blue_topnub=0x7f020023;
        public static final int com_facebook_tooltip_blue_xout=0x7f020024;
        public static final int com_facebook_top_background=0x7f020025;
        public static final int com_facebook_top_button=0x7f020026;
        public static final int com_facebook_usersettingsfragment_background_gradient=0x7f020027;
        public static final int icon=0x7f020028;
        public static final int launcher_icon=0x7f020029;
        public static final int screen=0x7f02002a;
        public static final int share_via_barcode=0x7f02002b;
        public static final int shopper_icon=0x7f02002c;
    }
    public static final class id {
        public static final int back_button=0x7f060036;
        public static final int barcode_image_view=0x7f06000f;
        public static final int bookmark_title=0x7f06000a;
        public static final int bookmark_url=0x7f06000b;
        public static final int com_facebook_body_frame=0x7f06002c;
        public static final int com_facebook_button_xout=0x7f06002e;
        public static final int com_facebook_login_activity_progress_bar=0x7f06001c;
        public static final int com_facebook_picker_activity_circle=0x7f06001b;
        public static final int com_facebook_picker_checkbox=0x7f06001e;
        public static final int com_facebook_picker_checkbox_stub=0x7f060022;
        public static final int com_facebook_picker_divider=0x7f060026;
        public static final int com_facebook_picker_done_button=0x7f060025;
        public static final int com_facebook_picker_image=0x7f06001f;
        public static final int com_facebook_picker_list_section_header=0x7f060023;
        public static final int com_facebook_picker_list_view=0x7f06001a;
        public static final int com_facebook_picker_profile_pic_stub=0x7f060020;
        public static final int com_facebook_picker_row_activity_circle=0x7f06001d;
        public static final int com_facebook_picker_search_text=0x7f06002b;
        public static final int com_facebook_picker_title=0x7f060021;
        public static final int com_facebook_picker_title_bar=0x7f060028;
        public static final int com_facebook_picker_title_bar_stub=0x7f060027;
        public static final int com_facebook_picker_top_bar=0x7f060024;
        public static final int com_facebook_search_bar_view=0x7f06002a;
        public static final int com_facebook_tooltip_bubble_view_bottom_pointer=0x7f060030;
        public static final int com_facebook_tooltip_bubble_view_text_body=0x7f06002f;
        public static final int com_facebook_tooltip_bubble_view_top_pointer=0x7f06002d;
        public static final int com_facebook_usersettingsfragment_login_button=0x7f060033;
        public static final int com_facebook_usersettingsfragment_logo_image=0x7f060031;
        public static final int com_facebook_usersettingsfragment_profile_name=0x7f060032;
        public static final int contents_supplement_text_view=0x7f060016;
        public static final int contents_text_view=0x7f060015;
        public static final int decode=0x7f060003;
        public static final int decode_failed=0x7f060004;
        public static final int decode_succeeded=0x7f060005;
        public static final int done_button=0x7f060037;
        public static final int format_text_view=0x7f060010;
        public static final int help_contents=0x7f060035;
        public static final int history_detail=0x7f060039;
        public static final int history_title=0x7f060038;
        public static final int image_view=0x7f060034;
        public static final int large=0x7f060002;
        public static final int launch_product_query=0x7f060006;
        public static final int menu_history_clear_text=0x7f060045;
        public static final int menu_history_send=0x7f060044;
        public static final int meta_text_view=0x7f060014;
        public static final int meta_text_view_label=0x7f060013;
        public static final int normal=0x7f060001;
        public static final int page_number_view=0x7f06003d;
        public static final int picker_subtitle=0x7f060029;
        public static final int preview_view=0x7f06000c;
        public static final int query_button=0x7f06003b;
        public static final int query_text_view=0x7f06003a;
        public static final int quit=0x7f060007;
        public static final int restart_preview=0x7f060008;
        public static final int result_button_view=0x7f060017;
        public static final int result_list_view=0x7f06003c;
        public static final int result_view=0x7f06000e;
        public static final int return_scan_result=0x7f060009;
        public static final int share_app_button=0x7f06003f;
        public static final int share_bookmark_button=0x7f060040;
        public static final int share_clipboard_button=0x7f060042;
        public static final int share_contact_button=0x7f060041;
        public static final int share_text_view=0x7f060043;
        public static final int shopper_button=0x7f060018;
        public static final int small=0x7f060000;
        public static final int snippet_view=0x7f06003e;
        public static final int status_view=0x7f060019;
        public static final int time_text_view=0x7f060012;
        public static final int type_text_view=0x7f060011;
        public static final int viewfinder_view=0x7f06000d;
    }
    public static final class layout {
        public static final int bookmark_picker_list_item=0x7f030000;
        public static final int capture=0x7f030001;
        public static final int com_facebook_friendpickerfragment=0x7f030002;
        public static final int com_facebook_login_activity_layout=0x7f030003;
        public static final int com_facebook_picker_activity_circle_row=0x7f030004;
        public static final int com_facebook_picker_checkbox=0x7f030005;
        public static final int com_facebook_picker_image=0x7f030006;
        public static final int com_facebook_picker_list_row=0x7f030007;
        public static final int com_facebook_picker_list_section_header=0x7f030008;
        public static final int com_facebook_picker_search_box=0x7f030009;
        public static final int com_facebook_picker_title_bar=0x7f03000a;
        public static final int com_facebook_picker_title_bar_stub=0x7f03000b;
        public static final int com_facebook_placepickerfragment=0x7f03000c;
        public static final int com_facebook_placepickerfragment_list_row=0x7f03000d;
        public static final int com_facebook_search_bar_layout=0x7f03000e;
        public static final int com_facebook_tooltip_bubble=0x7f03000f;
        public static final int com_facebook_usersettingsfragment=0x7f030010;
        public static final int encode=0x7f030011;
        public static final int help=0x7f030012;
        public static final int history_list_item=0x7f030013;
        public static final int search_book_contents=0x7f030014;
        public static final int search_book_contents_header=0x7f030015;
        public static final int search_book_contents_list_item=0x7f030016;
        public static final int share=0x7f030017;
    }
    public static final class menu {
        public static final int capture=0x7f0c0000;
        public static final int encode=0x7f0c0001;
        public static final int history=0x7f0c0002;
    }
    public static final class raw {
        public static final int beep=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f09001c;
        /**  <string name="app_name">ماسح الرمز الشريطي</string> 
 <string name="app_name">Баркод Скенер</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barra-kode Eskanerra</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">סורק ברקודים</string> 
 <string name="app_name">बारकोड स्कैनर</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">סורק ברקודים</string> 
 <string name="app_name">QRコードスキャナー</string> 
 <string name="app_name">바코드 스캐너</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Сканер штрих-кодов</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barkod Tarayıcısı</string> 
 <string name="app_name">条码扫描器</string> 
 <string name="app_name">條碼掃描器</string> 
         */
        public static final int app_picker_name=0x7f09001d;
        public static final int bookmark_picker_name=0x7f09001e;
        public static final int button_add_calendar=0x7f09001f;
        public static final int button_add_contact=0x7f090020;
        public static final int button_back=0x7f090021;
        public static final int button_book_search=0x7f090022;
        public static final int button_cancel=0x7f090023;
        public static final int button_custom_product_search=0x7f090024;
        public static final int button_dial=0x7f090025;
        public static final int button_done=0x7f090026;
        public static final int button_email=0x7f090027;
        public static final int button_get_directions=0x7f090028;
        public static final int button_google_shopper=0x7f090029;
        public static final int button_mms=0x7f09002a;
        public static final int button_ok=0x7f09002b;
        public static final int button_open_browser=0x7f09002c;
        public static final int button_product_search=0x7f09002d;
        public static final int button_search_book_contents=0x7f09002e;
        public static final int button_share_app=0x7f09002f;
        public static final int button_share_bookmark=0x7f090030;
        public static final int button_share_by_email=0x7f090031;
        public static final int button_share_by_sms=0x7f090032;
        public static final int button_share_clipboard=0x7f090033;
        public static final int button_share_contact=0x7f090034;
        public static final int button_show_map=0x7f090035;
        public static final int button_sms=0x7f090036;
        public static final int button_web_search=0x7f090037;
        public static final int button_wifi=0x7f090038;
        public static final int com_facebook_choose_friends=0x7f09000f;
        public static final int com_facebook_dialogloginactivity_ok_button=0x7f090000;
        public static final int com_facebook_internet_permission_error_message=0x7f090013;
        public static final int com_facebook_internet_permission_error_title=0x7f090012;
        public static final int com_facebook_loading=0x7f090011;
        public static final int com_facebook_loginview_cancel_action=0x7f090006;
        public static final int com_facebook_loginview_log_in_button=0x7f090002;
        public static final int com_facebook_loginview_log_out_action=0x7f090005;
        public static final int com_facebook_loginview_log_out_button=0x7f090001;
        public static final int com_facebook_loginview_logged_in_as=0x7f090003;
        public static final int com_facebook_loginview_logged_in_using_facebook=0x7f090004;
        public static final int com_facebook_logo_content_description=0x7f090007;
        public static final int com_facebook_nearby=0x7f090010;
        public static final int com_facebook_picker_done_button_text=0x7f09000e;
        public static final int com_facebook_placepicker_subtitle_catetory_only_format=0x7f09000c;
        public static final int com_facebook_placepicker_subtitle_format=0x7f09000b;
        public static final int com_facebook_placepicker_subtitle_were_here_only_format=0x7f09000d;
        public static final int com_facebook_requesterror_password_changed=0x7f090016;
        public static final int com_facebook_requesterror_permissions=0x7f090018;
        public static final int com_facebook_requesterror_reconnect=0x7f090017;
        public static final int com_facebook_requesterror_relogin=0x7f090015;
        public static final int com_facebook_requesterror_web_login=0x7f090014;
        public static final int com_facebook_tooltip_default=0x7f090019;
        public static final int com_facebook_usersettingsfragment_log_in_button=0x7f090008;
        public static final int com_facebook_usersettingsfragment_logged_in=0x7f090009;
        public static final int com_facebook_usersettingsfragment_not_logged_in=0x7f09000a;
        public static final int contents_contact=0x7f090039;
        public static final int contents_email=0x7f09003a;
        public static final int contents_location=0x7f09003b;
        public static final int contents_phone=0x7f09003c;
        public static final int contents_sms=0x7f09003d;
        public static final int contents_text=0x7f09003e;
        public static final int fb_app_id=0x7f09001a;
        public static final int fb_app_name=0x7f09001b;
        public static final int history_clear_one_history_text=0x7f090040;
        public static final int history_clear_text=0x7f09003f;
        public static final int history_email_title=0x7f090041;
        public static final int history_empty=0x7f090042;
        public static final int history_empty_detail=0x7f090043;
        public static final int history_send=0x7f090044;
        public static final int history_title=0x7f090045;
        public static final int menu_encode_mecard=0x7f090046;
        public static final int menu_encode_vcard=0x7f090047;
        public static final int menu_help=0x7f090048;
        public static final int menu_history=0x7f090049;
        public static final int menu_settings=0x7f090094;
        public static final int menu_share=0x7f09004a;
        public static final int msg_bulk_mode_scanned=0x7f09004b;
        public static final int msg_camera_framework_bug=0x7f09004c;
        public static final int msg_default_format=0x7f09004d;
        public static final int msg_default_meta=0x7f09004e;
        public static final int msg_default_mms_subject=0x7f09004f;
        public static final int msg_default_status=0x7f090050;
        public static final int msg_default_time=0x7f090051;
        public static final int msg_default_type=0x7f090052;
        public static final int msg_encode_contents_failed=0x7f090053;
        public static final int msg_google_books=0x7f090054;
        public static final int msg_google_product=0x7f090055;
        public static final int msg_google_shopper_missing=0x7f090056;
        public static final int msg_install_google_shopper=0x7f090057;
        public static final int msg_intent_failed=0x7f090058;
        public static final int msg_redirect=0x7f090059;
        public static final int msg_sbc_book_not_searchable=0x7f09005a;
        public static final int msg_sbc_failed=0x7f09005b;
        public static final int msg_sbc_no_page_returned=0x7f09005c;
        public static final int msg_sbc_page=0x7f09005d;
        public static final int msg_sbc_results=0x7f09005e;
        public static final int msg_sbc_searching_book=0x7f09005f;
        public static final int msg_sbc_snippet_unavailable=0x7f090060;
        public static final int msg_sbc_unknown_page=0x7f090061;
        public static final int msg_share_explanation=0x7f090062;
        public static final int msg_share_subject_line=0x7f090063;
        public static final int msg_share_text=0x7f090064;
        public static final int msg_sure=0x7f090065;
        public static final int msg_unmount_usb=0x7f090066;
        public static final int preferences_actions_title=0x7f090067;
        public static final int preferences_auto_focus_title=0x7f090068;
        public static final int preferences_bulk_mode_summary=0x7f090069;
        public static final int preferences_bulk_mode_title=0x7f09006a;
        public static final int preferences_copy_to_clipboard_title=0x7f09006b;
        public static final int preferences_custom_product_search_summary=0x7f09006c;
        public static final int preferences_custom_product_search_title=0x7f09006d;
        public static final int preferences_decode_1D_title=0x7f09006e;
        public static final int preferences_decode_Data_Matrix_title=0x7f09006f;
        public static final int preferences_decode_QR_title=0x7f090070;
        public static final int preferences_device_bug_workarounds_title=0x7f090071;
        public static final int preferences_disable_continuous_focus_summary=0x7f090072;
        public static final int preferences_disable_continuous_focus_title=0x7f090073;
        public static final int preferences_disable_exposure_title=0x7f090074;
        public static final int preferences_front_light_summary=0x7f090075;
        public static final int preferences_front_light_title=0x7f090076;
        public static final int preferences_general_title=0x7f090077;
        public static final int preferences_name=0x7f090078;
        public static final int preferences_play_beep_title=0x7f090079;
        public static final int preferences_remember_duplicates_summary=0x7f09007a;
        public static final int preferences_remember_duplicates_title=0x7f09007b;
        public static final int preferences_result_title=0x7f09007c;
        public static final int preferences_scanning_title=0x7f09007d;
        public static final int preferences_search_country=0x7f09007e;
        public static final int preferences_supplemental_summary=0x7f090081;
        public static final int preferences_supplemental_title=0x7f090082;
        public static final int preferences_try_bsplus=0x7f09007f;
        public static final int preferences_try_bsplus_summary=0x7f090080;
        public static final int preferences_vibrate_title=0x7f090083;
        public static final int result_address_book=0x7f090084;
        public static final int result_calendar=0x7f090085;
        public static final int result_email_address=0x7f090086;
        public static final int result_geo=0x7f090087;
        public static final int result_isbn=0x7f090088;
        public static final int result_product=0x7f090089;
        public static final int result_sms=0x7f09008a;
        public static final int result_tel=0x7f09008b;
        public static final int result_text=0x7f09008c;
        public static final int result_uri=0x7f09008d;
        public static final int result_wifi=0x7f09008e;
        public static final int sbc_name=0x7f09008f;
        public static final int share_name=0x7f090090;
        public static final int wifi_changing_network=0x7f090091;
        public static final int wifi_ssid_label=0x7f090092;
        public static final int wifi_type_label=0x7f090093;
    }
    public static final class style {
        public static final int com_facebook_loginview_default_style=0x7f0a0000;
        public static final int com_facebook_loginview_silver_style=0x7f0a0001;
        public static final int tooltip_bubble_text=0x7f0a0002;
    }
    public static final class xml {
        public static final int config=0x7f040000;
        public static final int preferences=0x7f040001;
    }
    public static final class styleable {
        /** Attributes that can be used with a com_facebook_friend_picker_fragment.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_friend_picker_fragment_multi_select com.pomelo.tell:multi_select}</code></td><td></td></tr>
           </table>
           @see #com_facebook_friend_picker_fragment_multi_select
         */
        public static final int[] com_facebook_friend_picker_fragment = {
            0x7f010007
        };
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#multi_select}
          attribute's value can be found in the {@link #com_facebook_friend_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:multi_select
        */
        public static final int com_facebook_friend_picker_fragment_multi_select = 0;
        /** Attributes that can be used with a com_facebook_login_view.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_login_view_confirm_logout com.pomelo.tell:confirm_logout}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_login_view_fetch_user_info com.pomelo.tell:fetch_user_info}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_login_view_login_text com.pomelo.tell:login_text}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_login_view_logout_text com.pomelo.tell:logout_text}</code></td><td></td></tr>
           </table>
           @see #com_facebook_login_view_confirm_logout
           @see #com_facebook_login_view_fetch_user_info
           @see #com_facebook_login_view_login_text
           @see #com_facebook_login_view_logout_text
         */
        public static final int[] com_facebook_login_view = {
            0x7f01000c, 0x7f01000d, 0x7f01000e, 0x7f01000f
        };
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#confirm_logout}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:confirm_logout
        */
        public static final int com_facebook_login_view_confirm_logout = 0;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#fetch_user_info}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:fetch_user_info
        */
        public static final int com_facebook_login_view_fetch_user_info = 1;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#login_text}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:login_text
        */
        public static final int com_facebook_login_view_login_text = 2;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#logout_text}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:logout_text
        */
        public static final int com_facebook_login_view_logout_text = 3;
        /** Attributes that can be used with a com_facebook_picker_fragment.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_done_button_background com.pomelo.tell:done_button_background}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_done_button_text com.pomelo.tell:done_button_text}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_extra_fields com.pomelo.tell:extra_fields}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_show_pictures com.pomelo.tell:show_pictures}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_show_title_bar com.pomelo.tell:show_title_bar}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_title_bar_background com.pomelo.tell:title_bar_background}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_title_text com.pomelo.tell:title_text}</code></td><td></td></tr>
           </table>
           @see #com_facebook_picker_fragment_done_button_background
           @see #com_facebook_picker_fragment_done_button_text
           @see #com_facebook_picker_fragment_extra_fields
           @see #com_facebook_picker_fragment_show_pictures
           @see #com_facebook_picker_fragment_show_title_bar
           @see #com_facebook_picker_fragment_title_bar_background
           @see #com_facebook_picker_fragment_title_text
         */
        public static final int[] com_facebook_picker_fragment = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006
        };
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#done_button_background}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.pomelo.tell:done_button_background
        */
        public static final int com_facebook_picker_fragment_done_button_background = 6;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#done_button_text}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:done_button_text
        */
        public static final int com_facebook_picker_fragment_done_button_text = 4;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#extra_fields}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:extra_fields
        */
        public static final int com_facebook_picker_fragment_extra_fields = 1;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#show_pictures}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:show_pictures
        */
        public static final int com_facebook_picker_fragment_show_pictures = 0;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#show_title_bar}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:show_title_bar
        */
        public static final int com_facebook_picker_fragment_show_title_bar = 2;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#title_bar_background}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name com.pomelo.tell:title_bar_background
        */
        public static final int com_facebook_picker_fragment_title_bar_background = 5;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#title_text}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:title_text
        */
        public static final int com_facebook_picker_fragment_title_text = 3;
        /** Attributes that can be used with a com_facebook_place_picker_fragment.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_radius_in_meters com.pomelo.tell:radius_in_meters}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_results_limit com.pomelo.tell:results_limit}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_search_text com.pomelo.tell:search_text}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_show_search_box com.pomelo.tell:show_search_box}</code></td><td></td></tr>
           </table>
           @see #com_facebook_place_picker_fragment_radius_in_meters
           @see #com_facebook_place_picker_fragment_results_limit
           @see #com_facebook_place_picker_fragment_search_text
           @see #com_facebook_place_picker_fragment_show_search_box
         */
        public static final int[] com_facebook_place_picker_fragment = {
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b
        };
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#radius_in_meters}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:radius_in_meters
        */
        public static final int com_facebook_place_picker_fragment_radius_in_meters = 0;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#results_limit}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:results_limit
        */
        public static final int com_facebook_place_picker_fragment_results_limit = 1;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#search_text}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:search_text
        */
        public static final int com_facebook_place_picker_fragment_search_text = 2;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#show_search_box}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:show_search_box
        */
        public static final int com_facebook_place_picker_fragment_show_search_box = 3;
        /** Attributes that can be used with a com_facebook_profile_picture_view.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_profile_picture_view_is_cropped com.pomelo.tell:is_cropped}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_profile_picture_view_preset_size com.pomelo.tell:preset_size}</code></td><td></td></tr>
           </table>
           @see #com_facebook_profile_picture_view_is_cropped
           @see #com_facebook_profile_picture_view_preset_size
         */
        public static final int[] com_facebook_profile_picture_view = {
            0x7f010010, 0x7f010011
        };
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#is_cropped}
          attribute's value can be found in the {@link #com_facebook_profile_picture_view} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name com.pomelo.tell:is_cropped
        */
        public static final int com_facebook_profile_picture_view_is_cropped = 1;
        /**
          <p>This symbol is the offset where the {@link com.pomelo.tell.R.attr#preset_size}
          attribute's value can be found in the {@link #com_facebook_profile_picture_view} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>small</code></td><td>-2</td><td> Keep in sync with constants in ProfilePictureView </td></tr>
<tr><td><code>normal</code></td><td>-3</td><td></td></tr>
<tr><td><code>large</code></td><td>-4</td><td></td></tr>
</table>
          @attr name com.pomelo.tell:preset_size
        */
        public static final int com_facebook_profile_picture_view_preset_size = 0;
    };
}
